version: '3.4'

services:
  woolly:
    image: docker.io/jcotton42/woolly
    build:
      context: .
      dockerfile: src/Woolly/Dockerfile
    configs:
      - source: woolly-config
        target: /app/appsettings.json
    secrets:
      - source: woolly-discord-token
        target: Discord:ApiToken
      - source: vanilla-rcon-password
        target: Minecraft:Servers:vanilla:RconPassword

  vanilla:
    image: docker.io/itzg/minecraft-server:java8
    environment:
      - EULA=TRUE
      - ENABLE_RCON=true
      - VERSION=1.12.2
      - UID=997
      - GID=997
      - RCON_PASSWORD_FILE=/run/secrets/vanilla-rcon-password
    ports:
      - 25565:25565
    volumes:
      - vanilla-data:/data
    secrets:
      - vanilla-rcon-password

configs:
  woolly-config:
    external: true

secrets:
  vanilla-rcon-password:
    external: true
  woolly-discord-token:
    external: true

volumes:
  vanilla-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/lib/minecraft/vanilla
