services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile

    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
  # user: root
  rcon-web:
    image: docker.io/itzg/rcon:latest
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: minecraft
      RWA_RCON_PASSWORD: password
